#!/bin/bash
input_file="$@"
output_file="${input_file%.*}.10MiB.mp4"

DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$input_file")

BITRATE=$(echo "75000 / $DURATION" | bc)

VIDEO_BITRATE="$(echo "$BITRATE - 128" | bc)k"

PRESET=veryslow

ffmpeg -y -i "$input_file" -vf scale=1280:720 -c:v libx264 -b:v $VIDEO_BITRATE -preset $PRESET -movflags +faststart -pass 1 -vsync cfr -f null /dev/null && \
ffmpeg -i "$input_file" -vf scale=1280:720 -c:v libx264 -b:v $VIDEO_BITRATE -preset $PRESET -movflags +faststart -pass 2 -c:a copy "$output_file"
